// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 27/11/2025, 5:39:42 p.m.
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/matyc/OneDrive/Escritorio/BeltranBrione/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/matyc/OneDrive/Escritorio/BeltranBrione/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/matyc/OneDrive/Escritorio/BeltranBrione/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/matyc/OneDrive/Escritorio/BeltranBrione/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/matyc/OneDrive/Escritorio/BeltranBrione/plugins/**/*.{js,ts,mjs}","C:/Users/matyc/OneDrive/Escritorio/BeltranBrione/composables/**/*.{js,ts,mjs}","C:/Users/matyc/OneDrive/Escritorio/BeltranBrione/utils/**/*.{js,ts,mjs}","C:/Users/matyc/OneDrive/Escritorio/BeltranBrione/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/matyc/OneDrive/Escritorio/BeltranBrione/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/matyc/OneDrive/Escritorio/BeltranBrione/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/matyc/OneDrive/Escritorio/BeltranBrione/app.config.{js,ts,mjs}","C:/Users/matyc/OneDrive/Escritorio/BeltranBrione/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;